### ISSUE TITLE
直播卡顿

### ISSUE THREAD

**Issue by Xuchenhao** [chenxuuu/24h-raspberry-live-on-bilibili#29]
FFMPEG的信息是frame=   92 fps=0.6 q=-0.0 size=    1042kB time=00:00:30.00 bitrate= 284.6kbits/
是否意味着树莓派的性能太低了以至于拖不起这个直播间

**Comment by chenxuuu** [comment]
@Xuchenhao 日志能截全吗？

**Comment by Xuchenhao** [comment]
![image](https://user-images.githubusercontent.com/10474077/35777534-7be65448-09ea-11e8-9f39-ff82dfd3252f.png)
这是当前输出的

**Comment by chenxuuu** [comment]
从一开始执行ffmpeg的命令到最下面都复制过来可以吗？
用代码格式
```
像这样
123123
```

**Comment by Xuchenhao** [comment]
```
ffmpeg version 3.2.10-1~deb9u1+rpt1 Copyright (c) 2000-2018 the FFmpeg developer                                                                                                 s
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1+rpt1' --toolchain=harde                                                                                                 ned --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueab                                                                                                 ihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --ena                                                                                                 ble-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b -                                                                                                 -enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-                                                                                                 libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-                                                                                                 libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-lib                                                                                                 opus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnap                                                                                                 py --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enabl                                                                                                 e-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-lib                                                                                                 webp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable                                                                                                 -omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-li                                                                                                 bdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libop                                                                                                 encv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, image2, from '/home/pi/live/default_pic/aa.jpg':
  Duration: 00:00:00.33, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 1600x1200                                                                                                  [SAR 28:28 DAR 4:3], 3 fps, 3 tbr, 3 tbn, 3 tbc
Input #1, mp3, from '/home/pi/live/default_mp3/こじまめぐみ (こじまめぐみ) - FRU                                                                                                 ITS CANDY (NHKアニメーション カードキャプターさくら 新エンディングテーマ).mp3':
  Metadata:
    ID              : 8591811488
    title           : FRUITS CANDY (NHKアニメーション カードキャプターさくら 新                                                                                                 エンディングテーマ)
    artist          : こじまめぐみ (こじまめぐみ)
    album           : FRUITS CANDY
    track           : 1
    disc            : 0
    genre           : Blues
  Duration: 00:03:43.66, start: 0.025056, bitrate: 323 kb/s
    Stream #1:0: Audio: mp3, 44100 Hz, stereo, s16p, 320 kb/s
    Metadata:
      encoder         : LAME3.98r
    Side data:
      replaygain: track gain - -9.300000, track peak - unknown, album gain - unk                                                                                                 nown, album peak - unknown,
    Stream #1:1: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 500x500 [S                                                                                                 AR 96:96 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
Codec AVOption preset (Configuration preset) specified for output file #0 (rtmp:                                                                                                 //qn.live-send.acg.tv/live-qn/?streamname=live_3459441_7167258&key=774ba509c1e16                                                                                                 5c07d30eb5d1c8e82ba) has not been used for any stream. The most likely reason is                                                                                                  either wrong type (e.g. a video option with no video streams) or that it is a p                                                                                                 rivate option of some encoder which was not actually used for any stream.
[Parsed_ass_0 @ 0x1438d00] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.4.2 (CO                                                                                                 MPLEX)
[Parsed_ass_0 @ 0x1438d00] Using font provider fontconfig
[Parsed_ass_0 @ 0x1438d00] Added subtitle file: '/home/pi/live/default.ass' (6 s                                                                                                 tyles, 4 events)
[swscaler @ 0x148bd90] deprecated pixel format used, make sure you did set range                                                                                                  correctly
[h264_omx @ 0x14348a0] Using OMX.broadcom.video_encode
Output #0, flv, to 'rtmp://qn.live-send.acg.tv/live-qn/?streamname=live_3459441_                                                                                                 7167258&key=774ba509c1e165c07d30eb5d1c8e82ba':
  Metadata:
    encoder         : Lavf57.56.101
    Stream #0:0: Video: h264 (h264_omx) ([7][0][0][0] / 0x0007), yuv420p, 1600x1                                                                                                 200 [SAR 1:1 DAR 4:3], q=2-31, 200 kb/s, 3 fps, 1k tbn, 3 tbc
    Metadata:
      encoder         : Lavc57.64.101 h264_omx
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, flt                                                                                                 p, 192 kb/s
    Metadata:
      encoder         : Lavc57.64.101 aac
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (h264_omx))
  Stream #1:0 -> #0:1 (mp3 (native) -> aac (native))
Press [q] to stop, [?] for help
[image2 @ 0x142a300] Thread message queue blocking; consider raising the thread_                                                                                                 queue_size option (current value: 8)
[Parsed_ass_0 @ 0x1438d00] fontselect: (微软雅黑, 400, 0) -> /usr/share/fonts/tr                                                                                                 uetype/dejavu/DejaVuSans.ttf, 0, DejaVuSans
[Parsed_ass_0 @ 0x1438d00] Glyph 0x5F53 not found, selecting one more font for (                                                                                                 微软雅黑, 400, 0)
[Parsed_ass_0 @ 0x1438d00] fontselect: (微软雅黑, 400, 0) -> /usr/share/fonts/tr                                                                                                 uetype/wqy/wqy-microhei.ttc, 0, WenQuanYiMicroHei
frame=    2 fps=1.3 q=-0.0 size=       0kB time=00:00:00.00 bitrate=2848.0kbits/                                                                                                 frame=    2 fps=0.7 q=-0.0 size=       0kB time=00:00:00.00 bitrate=2848.0kbits/                                                                                                 frame=    3 fps=0.7 q=-0.0 size=      18kB time=00:00:00.33 bitrate= 436.6kbits/                                                                                                 frame=    4 fps=0.7 q=-0.0 size=      20kB time=00:00:00.66 bitrate= 244.6kbits/                                                                                                 frame=    5 fps=0.7 q=-0.0 size=      21kB time=00:00:01.00 bitrate= 170.6kbits/                                                                                                 frame=    5 fps=0.7 q=-0.0 size=      25kB time=00:00:01.04 bitrate= 192.7kbits/                                                                                                 frame=    6 fps=0.7 q=-0.0 size=      26kB time=00:00:01.33 bitrate= 160.6kbits/                                                                                                 frame=    7 fps=0.7 q=-0.0 size=      35kB time=00:00:01.66 bitrate= 171.3kbits/                                                                                                 frame=    8 fps=0.7 q=-0.0 size=      42kB time=00:00:02.00 bitrate= 173.1kbits/                                                                                                 frame=    9 fps=0.6 q=-0.0 size=      51kB time=00:00:02.33 bitrate= 178.6kbits/                                                                                                 frame=    9 fps=0.6 q=-0.0 size=      58kB time=00:00:02.34 bitrate= 201.8kbits/                                                                                                 frame=   10 fps=0.6 q=-0.0 size=      59kB time=00:00:02.66 bitrate= 181.1kbits/                                                                                                 frame=   10 fps=0.6 q=-0.0 size=      64kB time=00:00:02.66 bitrate= 196.6kbits/                                                                                                 frame=   11 fps=0.6 q=-0.0 size=      67kB time=00:00:03.00 bitrate= 182.7kbits/                                                                                                 frame=   11 fps=0.6 q=-0.0 size=      72kB time=00:00:03.00 bitrate= 196.4kbits/                                                                                                 frame=   37 fps=0.5 q=-0.0 Lsize=     369kB time=00:00:12.00 bitrate= 252.0kbits/s speed=0.177x
video:106kB audio:254kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.619442%
[aac @ 0x14316b0] Qavg: 6101.416
Exiting normally, received signal 2.
^CTraceback (most recent call last):
  File "play.py", line 92, in <module>
    audio = MP3(path+'/default_mp3/'+mp3_files[mp3_ran])    #获取mp3文件信息
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_file.py", line 49, in __init__
    self.load(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_util.py", line 140, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/id3/_file.py", line 394, in load
    self.tags = ID3(fileobj, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/id3/_file.py", line 77, in __init__
    super(ID3, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/id3/_tags.py", line 177, in __init__
    super(ID3Tags, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_util.py", line 533, in __init__
    super(DictProxy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_tags.py", line 111, in __init__
    self.load(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_util.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_util.py", line 140, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/id3/_file.py", line 165, in load
    remaining_data = self._read(self._header, data)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/id3/_tags.py", line 183, in _read
    self._add(frame, False)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/id3/_tags.py", line 319, in _add
    self[hash_key] = new_frame
  File "/usr/local/lib/python3.5/dist-packages/mutagen/id3/_tags.py", line 344, in __setitem__
    super(ID3Tags, self).__setitem__(key, tag)
KeyboardInterrupt
^C
```

**Comment by chenxuuu** [comment]
按照readme里面把显存改大了吗？

**Comment by Xuchenhao** [comment]
已经设置成256M了

**Comment by Xuchenhao** [comment]
另外是否和FFmpeg的版本有关呢？我没有按照您的文档安装FFmpeg 我是直接从源里面安装的

**Comment by Xuchenhao** [comment]
x264是编译的

**Comment by chenxuuu** [comment]
最好按教程来
